In [3]:
import scipy
import numpy as np

In [4]:
signal = np.float32([[0.6, 0.2, 1.2, 0.4, 0.3],
                   [0.9, 1.7, 0.3, 1.1, 0.1],
                   [0.6, 0.8, 1.1, 0.2, 0.5],
                   [0.4, 0.1, 0.4, 0, 0.2]])

In [5]:
signal

array([[0.6, 0.2, 1.2, 0.4, 0.3],
       [0.9, 1.7, 0.3, 1.1, 0.1],
       [0.6, 0.8, 1.1, 0.2, 0.5],
       [0.4, 0.1, 0.4, 0. , 0.2]], dtype=float32)

In [7]:
h = np.zeros((3, 3))
h[1, 1] = 2
h = h-np.ones((3, 3))/9
h

array([[-0.11111111, -0.11111111, -0.11111111],
       [-0.11111111,  1.88888889, -0.11111111],
       [-0.11111111, -0.11111111, -0.11111111]])

In [10]:
from scipy.signal import sepfir2d
from scipy.signal import convolve2d

In [15]:
convolve2d(signal, h, mode='same')

array([[ 0.82222226, -0.14444445,  1.85555564,  0.42222222,  0.38888891],
       [ 1.26666661,  2.57777785, -0.17777777,  1.62222226, -0.08888889],
       [ 0.70000004,  0.90000001,  1.5666667 , -0.03333334,  0.76666666],
       [ 0.5888889 , -0.17777778,  0.51111112, -0.26666667,  0.30000001]])