In [46]:
import tensorflow.keras as K
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_iris
import tensorflow as tf
import tensorboard
from sklearn.metrics import confusion_matrix

In [47]:
def loadIrisData():
    iris = load_iris()
    X=iris['data']
    t=iris['target']
    print(X.shape)
    print(t.shape)
    return X, t
X, t = loadIrisData()
# np.insert(y,0,1,axis=0)

(150, 4)
(150,)


In [48]:
t

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
def one_hot_encoding(t_indices, N):
    '''
    Inputs:
        t_indices: list of indices
        N: total no. of classes
    '''
    assert N>max(t_indices), (N, max(t_indices))

    ### WRITE YOUR CODE HERE - 2 MARKS
    one_hot_encoded = np.zeros((len(t_indices), N))
    unique_list = np.unique(t_indices)
    
    for i in unique_list:
        idx = np.where(t_indices==i)[0]
#         print(idx)
        one_hot_encoded[idx, i] = 1

    t_1hot = one_hot_encoded
    return t_1hot
t = one_hot_encoding(t, 3)

In [50]:
def splitData(X,t,testFraction=0.2):
    """
    Use numpy functions only
    Inputs:
        X: np array of shape (Nsamples, dim)
        t: np array of len Nsamples; can be one hot vectors or labels
        testFraction: (float) Nsamples_test = testFraction * Nsamples
    """

    ### WRITE YOUR CODE HERE - 2 MARKS
#     print(np.floor(len(X)*testFraction))
    arr = np.arange(len(X))
    np.random.shuffle(arr)
    X = X[arr]
    t = t[arr]
    
    X_test = X[:int(np.floor(testFraction*len(X))), :]
    t_test = t[:int(np.floor(testFraction*len(t))), :]
    
    X_train = X[int(np.floor(testFraction*len(X))):, :]
    t_train = t[int(np.floor(testFraction*len(t))):, :]
    
    return X_train, t_train, X_test, t_test

X_train, t_train, X_test, t_test = splitData(X, t)

In [51]:
### Normalize data to be of zero mean and unit variance
def normalizeX(X_train, X_test):
    '''
    Inputs:
        X_train: np array 2d
        X_test: np array 2d
    Outputs:
        Normalized np arrays 2d
    '''

    ### WRITE YOUR CODE HERE - 2 MARKS
    
    X_test_normalized = (X_test-np.float32([np.mean(X_test, axis=0)]))
    X_test_normalized = X_test_normalized/np.float32([np.std(X_test_normalized, axis=0)])
    X_train_normalized = (X_train-np.float32([np.mean(X_train, axis=0)]))
    X_train_normalized = X_train_normalized/np.float32([np.std(X_train_normalized, axis=0)])

    return X_train_normalized, X_test_normalized

X_train, X_test = normalizeX(X_train, X_test)

## sigmoid model

In [101]:
model_s = tf.keras.Sequential()
model_s.add(tf.keras.layers.Dense(10, input_dim=4, activation=tf.keras.layers.Activation('sigmoid')))
model_s.add(tf.keras.layers.Dense(3, activation=tf.keras.layers.Activation('sigmoid')))

tensorboard_callback_s = tf.keras.callbacks.TensorBoard(log_dir='./logdir_sigmoid')

In [102]:
model_s.compile(optimizer=tf.optimizers.RMSprop(),
              loss='mean_squared_error',
              metrics=['accuracy'])

In [103]:
model_s.fit(x=X_train, y=t_train, validation_data=(X_test, t_test), epochs=100, callbacks=[tensorboard_callback_s])

Train on 120 samples, validate on 30 samples


W0923 13:56:29.928368 139682939295552 summary_ops_v2.py:1110] Model failed to serialize as JSON. Ignoring... 'Activation' object has no attribute '__name__'


Epoch 1/100
120/120 [==============================] - 1s 6ms/sample - loss: 0.2565 - accuracy: 0.3417 - val_loss: 0.2574 - val_accuracy: 0.3000
Epoch 2/100
120/120 [==============================] - 0s 101us/sample - loss: 0.2513 - accuracy: 0.3417 - val_loss: 0.2533 - val_accuracy: 0.3000
Epoch 3/100
120/120 [==============================] - 0s 95us/sample - loss: 0.2478 - accuracy: 0.3417 - val_loss: 0.2500 - val_accuracy: 0.3000
Epoch 4/100
120/120 [==============================] - 0s 129us/sample - loss: 0.2446 - accuracy: 0.3417 - val_loss: 0.2470 - val_accuracy: 0.3000
Epoch 5/100
120/120 [==============================] - 0s 89us/sample - loss: 0.2419 - accuracy: 0.3417 - val_loss: 0.2442 - val_accuracy: 0.3000
Epoch 6/100
120/120 [==============================] - 0s 84us/sample - loss: 0.2392 - accuracy: 0.3417 - val_loss: 0.2416 - val_accuracy: 0.3000
Epoch 7/100
120/120 [==============================] - 0s 91us/sample - loss: 0.2367 - accuracy: 0.3417 - val_loss: 0.2390 

In [104]:
%tensorboard --logdir=./logdir_sigmoid/

Reusing TensorBoard on port 6012 (pid 6871), started 0:28:23 ago. (Use '!kill 6871' to kill it.)

In [105]:
y_pred = model_s.predict(X_train)
y_pred_num_val = np.argmax(y_pred, axis=1)
t_val = np.argmax(t_train, axis=1)
print('for train values')
print(confusion_matrix(t_val, y_pred_num_val))

y_pred = model_s.predict(X_test)
y_pred_num_val = np.argmax(y_pred, axis=1)
t_val = np.argmax(t_test, axis=1)
print('for test values')
print(confusion_matrix(t_val, y_pred_num_val))

for train values
[[39  0  0]
 [ 0 17 23]
 [ 0  0 41]]
for test values
[[11  0  0]
 [ 0  4  6]
 [ 0  0  9]]


### Softmax model

In [106]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, input_dim=4, activation=tf.keras.layers.Activation('sigmoid')))
model.add(tf.keras.layers.Dense(3, activation=tf.keras.layers.Activation('softmax')))

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./logdir')

In [107]:
model.compile(optimizer=tf.optimizers.RMSprop(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [108]:
model.fit(x=X_train, y=t_train, validation_data=(X_test, t_test), epochs=100, callbacks=[tensorboard_callback])

Train on 120 samples, validate on 30 samples


W0923 13:57:36.451481 139682939295552 summary_ops_v2.py:1110] Model failed to serialize as JSON. Ignoring... 'Activation' object has no attribute '__name__'


Epoch 1/100
120/120 [==============================] - 0s 3ms/sample - loss: 1.1072 - accuracy: 0.1917 - val_loss: 1.0846 - val_accuracy: 0.3333
Epoch 2/100
120/120 [==============================] - 0s 152us/sample - loss: 1.0872 - accuracy: 0.2583 - val_loss: 1.0704 - val_accuracy: 0.4333
Epoch 3/100
120/120 [==============================] - 0s 173us/sample - loss: 1.0736 - accuracy: 0.3083 - val_loss: 1.0586 - val_accuracy: 0.5000
Epoch 4/100
120/120 [==============================] - 0s 109us/sample - loss: 1.0611 - accuracy: 0.3583 - val_loss: 1.0476 - val_accuracy: 0.5333
Epoch 5/100
120/120 [==============================] - 0s 84us/sample - loss: 1.0501 - accuracy: 0.3917 - val_loss: 1.0374 - val_accuracy: 0.5667
Epoch 6/100
120/120 [==============================] - 0s 95us/sample - loss: 1.0389 - accuracy: 0.4167 - val_loss: 1.0277 - val_accuracy: 0.5667
Epoch 7/100
120/120 [==============================] - 0s 104us/sample - loss: 1.0293 - accuracy: 0.5000 - val_loss: 1.018

In [109]:
# logdir='./logdir'
# %load_ext tensorboard
%tensorboard --logdir=./logdir/

Reusing TensorBoard on port 6011 (pid 6782), started 0:32:04 ago. (Use '!kill 6782' to kill it.)

In [110]:
y_pred = model.predict(X_train)
y_pred_num_val = np.argmax(y_pred, axis=1)
t_val = np.argmax(t_train, axis=1)
print('for train values')
print(confusion_matrix(t_val, y_pred_num_val))

y_pred = model.predict(X_test)
y_pred_num_val = np.argmax(y_pred, axis=1)
t_val = np.argmax(t_test, axis=1)
print('for test values')
print(confusion_matrix(t_val, y_pred_num_val))

for train values
[[39  0  0]
 [ 0 26 14]
 [ 0  3 38]]
for test values
[[11  0  0]
 [ 0  7  3]
 [ 0  2  7]]
